/**
 * Language grammar definitions for syntax highlighting.
 *
 * @module utils/syntaxHighlight/grammars
 */

import type { Grammar } from './types';


// =============================================================================
// GRAMMARS
// =============================================================================

/**
 * JavaScript/TypeScript grammar.
 */
export const GRAMMAR_RUST: Grammar = {
	name: 'rust',
	extensions: ['.rs'],
	keywords: new Set([
		'as',
		'async',
		'await',
		'break',
		'const',
		'continue',
		'crate',
		'dyn',
		'else',
		'enum',
		'extern',
		'false',
		'fn',
		'for',
		'if',
		'impl',
		'in',
		'let',
		'loop',
		'match',
		'mod',
		'move',
		'mut',
		'pub',
		'ref',
		'return',
		'self',
		'Self',
		'static',
		'struct',
		'super',
		'trait',
		'true',
		'type',
		'union',
		'unsafe',
		'use',
		'where',
		'while',
		'macro_rules',
	]),
	builtins: new Set([
		'Option',
		'Some',
		'None',
		'Result',
		'Ok',
		'Err',
		'Box',
		'Vec',
		'String',
		'HashMap',
		'HashSet',
		'Rc',
		'Arc',
		'RefCell',
		'Cell',
		'Mutex',
		'RwLock',
		'println',
		'eprintln',
		'print',
		'eprint',
		'format',
		'panic',
		'assert',
		'assert_eq',
		'assert_ne',
		'debug_assert',
		'todo',
		'unimplemented',
		'unreachable',
		'cfg',
		'derive',
	]),
	types: new Set([
		'bool',
		'char',
		'str',
		'u8',
		'u16',
		'u32',
		'u64',
		'u128',
		'usize',
		'i8',
		'i16',
		'i32',
		'i64',
		'i128',
		'isize',
		'f32',
		'f64',
		'()',
	]),
	constants: new Set(['true', 'false']),
	operators: /[+\-*/%=<>!&|^~?:@]+/,
	lineComment: '//',
	blockCommentStart: '/*',
	blockCommentEnd: '*/',
	stringDelimiters: ['"'],
	templateLiteralStart: null,
	templateLiteralEnd: null,
	numberPattern:
		/\b(?:0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+|(?:\d[\d_]*)?\.?\d[\d_]*(?:[eE][+-]?\d[\d_]*)?(?:_?(?:u8|u16|u32|u64|u128|usize|i8|i16|i32|i64|i128|isize|f32|f64))?)\b/,
	identifierPattern: /[a-zA-Z_][a-zA-Z0-9_]*/,
	nestedComments: true,
};

/**
 * Go grammar.
 */
export const GRAMMAR_GO: Grammar = {
	name: 'go',
	extensions: ['.go'],
	keywords: new Set([
		'break',
		'case',
		'chan',
		'const',
		'continue',
		'default',
		'defer',
		'else',
		'fallthrough',
		'for',
		'func',
		'go',
		'goto',
		'if',
		'import',
		'interface',
		'map',
		'package',
		'range',
		'return',
		'select',
		'struct',
		'switch',
		'type',
		'var',
	]),
	builtins: new Set([
		'append',
		'cap',
		'close',
		'complex',
		'copy',
		'delete',
		'imag',
		'len',
		'make',
		'new',
		'panic',
		'print',
		'println',
		'real',
		'recover',
	]),
	types: new Set([
		'bool',
		'byte',
		'complex64',
		'complex128',
		'error',
		'float32',
		'float64',
		'int',
		'int8',
		'int16',
		'int32',
		'int64',
		'rune',
		'string',
		'uint',
		'uint8',
		'uint16',
		'uint32',
		'uint64',
		'uintptr',
	]),
	constants: new Set(['true', 'false', 'nil', 'iota']),
	operators: /[+\-*/%=<>!&|^~:]+/,
	lineComment: '//',
	blockCommentStart: '/*',
	blockCommentEnd: '*/',
	stringDelimiters: ['"', "'", '`'],
	templateLiteralStart: null,
	templateLiteralEnd: null,
	numberPattern:
		/\b(?:0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+|(?:\d[\d_]*)?\.?\d[\d_]*(?:[eE][+-]?\d[\d_]*)?i?)\b/,
	identifierPattern: /[a-zA-Z_][a-zA-Z0-9_]*/,
	nestedComments: false,
};

/**
 * Shell/Bash grammar.
 */
