/**
 * Language grammar definitions for syntax highlighting.
 *
 * @module utils/syntaxHighlight/grammars
 */

import type { Grammar } from './types';

// =============================================================================
// GRAMMARS
// =============================================================================

/**
 * JavaScript/TypeScript grammar.
 */
export const GRAMMAR_JAVASCRIPT: Grammar = {
	name: 'javascript',
	extensions: ['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs'],
	keywords: new Set([
		'async',
		'await',
		'break',
		'case',
		'catch',
		'class',
		'const',
		'continue',
		'debugger',
		'default',
		'delete',
		'do',
		'else',
		'enum',
		'export',
		'extends',
		'finally',
		'for',
		'from',
		'function',
		'if',
		'implements',
		'import',
		'in',
		'instanceof',
		'interface',
		'let',
		'new',
		'of',
		'package',
		'private',
		'protected',
		'public',
		'return',
		'static',
		'super',
		'switch',
		'this',
		'throw',
		'try',
		'type',
		'typeof',
		'var',
		'void',
		'while',
		'with',
		'yield',
		'as',
		'is',
		'keyof',
		'readonly',
		'declare',
		'namespace',
		'abstract',
		'satisfies',
	]),
	builtins: new Set([
		'Array',
		'Boolean',
		'Date',
		'Error',
		'Function',
		'JSON',
		'Math',
		'Number',
		'Object',
		'Promise',
		'RegExp',
		'String',
		'Symbol',
		'Map',
		'Set',
		'WeakMap',
		'WeakSet',
		'console',
		'window',
		'document',
		'globalThis',
		'process',
		'require',
		'module',
		'exports',
		'Buffer',
		'setTimeout',
		'setInterval',
		'clearTimeout',
		'clearInterval',
		'fetch',
		'Response',
		'Request',
		'Headers',
		'URL',
		'URLSearchParams',
		'FormData',
		'Blob',
		'File',
		'FileReader',
		'Intl',
		'Proxy',
		'Reflect',
		'BigInt',
	]),
	types: new Set([
		'any',
		'boolean',
		'number',
		'string',
		'void',
		'never',
		'unknown',
		'null',
		'undefined',
		'object',
		'symbol',
		'bigint',
	]),
	constants: new Set(['true', 'false', 'null', 'undefined', 'NaN', 'Infinity']),
	operators: /[+\-*/%=<>!&|^~?:]+/,
	lineComment: '//',
	blockCommentStart: '/*',
	blockCommentEnd: '*/',
	stringDelimiters: ["'", '"'],
	templateLiteralStart: '`',
	templateLiteralEnd: '`',
	numberPattern:
		/\b(?:0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+|(?:\d[\d_]*)?\.?\d[\d_]*(?:[eE][+-]?\d[\d_]*)?n?)\b/,
	identifierPattern: /[a-zA-Z_$][a-zA-Z0-9_$]*/,
	nestedComments: false,
};

/**
 * Python grammar.
 */
export const GRAMMAR_PYTHON: Grammar = {
	name: 'python',
	extensions: ['.py', '.pyw', '.pyi'],
	keywords: new Set([
		'and',
		'as',
		'assert',
		'async',
		'await',
		'break',
		'class',
		'continue',
		'def',
		'del',
		'elif',
		'else',
		'except',
		'finally',
		'for',
		'from',
		'global',
		'if',
		'import',
		'in',
		'is',
		'lambda',
		'nonlocal',
		'not',
		'or',
		'pass',
		'raise',
		'return',
		'try',
		'while',
		'with',
		'yield',
		'match',
		'case',
	]),
	builtins: new Set([
		'abs',
		'all',
		'any',
		'ascii',
		'bin',
		'bool',
		'breakpoint',
		'bytearray',
		'bytes',
		'callable',
		'chr',
		'classmethod',
		'compile',
		'complex',
		'delattr',
		'dict',
		'dir',
		'divmod',
		'enumerate',
		'eval',
		'exec',
		'filter',
		'float',
		'format',
		'frozenset',
		'getattr',
		'globals',
		'hasattr',
		'hash',
		'help',
		'hex',
		'id',
		'input',
		'int',
		'isinstance',
		'issubclass',
		'iter',
		'len',
		'list',
		'locals',
		'map',
		'max',
		'memoryview',
		'min',
		'next',
		'object',
		'oct',
		'open',
		'ord',
		'pow',
		'print',
		'property',
		'range',
		'repr',
		'reversed',
		'round',
		'set',
		'setattr',
		'slice',
		'sorted',
		'staticmethod',
		'str',
		'sum',
		'super',
		'tuple',
		'type',
		'vars',
		'zip',
		'__import__',
	]),
	types: new Set(['int', 'float', 'str', 'bool', 'list', 'dict', 'set', 'tuple', 'bytes', 'None']),
	constants: new Set(['True', 'False', 'None', 'Ellipsis', 'NotImplemented', '__debug__']),
	operators: /[+\-*/%=<>!@&|^~:]+/,
	lineComment: '#',
	blockCommentStart: null,
	blockCommentEnd: null,
	stringDelimiters: ["'", '"', "'''", '"""'],
	templateLiteralStart: null,
	templateLiteralEnd: null,
	numberPattern:
		/\b(?:0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+|(?:\d[\d_]*)?\.?\d[\d_]*(?:[eE][+-]?\d[\d_]*)?[jJ]?)\b/,
	identifierPattern: /[a-zA-Z_][a-zA-Z0-9_]*/,
	nestedComments: false,
};

/**
 * Rust grammar.
 */
