/**
 * List component namespace.
 *
 * Provides all operations for list components including selection,
 * virtualization, search, and multi-select.
 *
 * @example
 * ```typescript
 * import { list } from 'blecsd/components';
 * list.attach(world, eid);
 * list.items.set(world, eid, items);
 * list.selection.next(world, eid);
 * ```
 */
import {
	activateSelected,
	addItem,
	appendItems,
	appendToSearchQuery,
	attachListBehavior,
	backspaceSearchQuery,
	blurList,
	checkNeedsLoad,
	clearItems,
	clearLazyLoadCallback,
	clearListCallbacks,
	clearListDisplay,
	clearListFilter,
	clearSearchQuery,
	clearSelection,
	deselectAllItems,
	disableList,
	enableList,
	endListSearch,
	ensureVisible,
	findAndSelectByText,
	findNextMatch,
	focusList,
	getFilteredItems,
	getFirstVisible,
	getItem,
	getItemCount,
	getItems,
	getLazyLoadCallback,
	getListDisplay,
	getListSearchQuery,
	getListState,
	getLoadingPlaceholder,
	getMultiSelected,
	getScrollInfo,
	getSelectedIndex,
	getSelectedItem,
	getTotalCount,
	getVisibleCount,
	getVisibleItems,
	handleListKeyPress,
	isItemMultiSelected,
	isList,
	isListDisabled,
	isListFocused,
	isListInState,
	isListInteractive,
	isListKeysEnabled,
	isListLoading,
	isListMouseEnabled,
	isListMultiSelect,
	isListSearchEnabled,
	isListSearching,
	loadItems,
	onListActivate,
	onListCancel,
	onListScroll,
	onListSearchChange,
	onListSelect,
	removeItem,
	renderListItems,
	scrollPage,
	selectAllItems,
	selectByValue,
	selectFirst,
	selectLast,
	selectNext,
	selectPrev,
	sendListEvent,
	setFirstVisible,
	setItems,
	setLazyLoadCallback,
	setListDisplay,
	setListFilter,
	setListInteractive,
	setListKeys,
	setListLoading,
	setListMouse,
	setListMultiSelect,
	setListSearchEnabled,
	setListSearchQuery,
	setLoadingPlaceholder,
	setSelectedIndex,
	setTotalCount,
	setVisibleCount,
	startListSearch,
	toggleMultiSelect,
	triggerListCancel,
	updateItem,
} from '../list';

export const list = Object.freeze({
	attach: attachListBehavior,
	is: isList,
	getState: getListState,
	isInState: isListInState,
	sendEvent: sendListEvent,
	handleKeyPress: handleListKeyPress,
	render: renderListItems,

	focus: focusList,
	blur: blurList,
	isFocused: isListFocused,

	enable: enableList,
	disable: disableList,
	isDisabled: isListDisabled,

	isInteractive: isListInteractive,
	setInteractive: setListInteractive,
	isKeysEnabled: isListKeysEnabled,
	setKeys: setListKeys,
	isMouseEnabled: isListMouseEnabled,
	setMouse: setListMouse,

	items: Object.freeze({
		get: getItems,
		set: setItems,
		getItem,
		getCount: getItemCount,
		add: addItem,
		remove: removeItem,
		update: updateItem,
		clear: clearItems,
		append: appendItems,
		getFiltered: getFilteredItems,
	}),

	selection: Object.freeze({
		getIndex: getSelectedIndex,
		setIndex: setSelectedIndex,
		getItem: getSelectedItem,
		activate: activateSelected,
		byValue: selectByValue,
		next: selectNext,
		prev: selectPrev,
		first: selectFirst,
		last: selectLast,
		clear: clearSelection,
	}),

	multiSelect: Object.freeze({
		isEnabled: isListMultiSelect,
		setEnabled: setListMultiSelect,
		toggle: toggleMultiSelect,
		getSelected: getMultiSelected,
		isItemSelected: isItemMultiSelected,
		selectAll: selectAllItems,
		deselectAll: deselectAllItems,
	}),

	search: Object.freeze({
		isEnabled: isListSearchEnabled,
		setEnabled: setListSearchEnabled,
		isSearching: isListSearching,
		start: startListSearch,
		end: endListSearch,
		getQuery: getListSearchQuery,
		setQuery: setListSearchQuery,
		appendToQuery: appendToSearchQuery,
		backspace: backspaceSearchQuery,
		clearQuery: clearSearchQuery,
		findAndSelect: findAndSelectByText,
		findNext: findNextMatch,
		onChange: onListSearchChange,
	}),

	filter: Object.freeze({
		set: setListFilter,
		clear: clearListFilter,
	}),

	virtualization: Object.freeze({
		getScrollInfo,
		ensureVisible,
		scrollPage,
		getFirstVisible,
		setFirstVisible,
		getVisibleCount,
		setVisibleCount,
		getVisibleItems,
		getTotalCount,
		setTotalCount,

		isLoading: isListLoading,
		setLoading: setListLoading,
		getLoadingPlaceholder,
		setLoadingPlaceholder,
		loadItems,
		checkNeedsLoad,
		getLazyLoadCallback,
		setLazyLoadCallback,
		clearLazyLoadCallback,
	}),

	display: Object.freeze({
		get: getListDisplay,
		set: setListDisplay,
		clear: clearListDisplay,
	}),

	callbacks: Object.freeze({
		onSelect: onListSelect,
		onActivate: onListActivate,
		onCancel: onListCancel,
		onScroll: onListScroll,
		triggerCancel: triggerListCancel,
		clear: clearListCallbacks,
	}),
});

export type ListModule = typeof list;
