/**
 * Input components (interactive, focusable, input, textInput)
 * @module components/exports/input
 */

// Focusable component
export type { FocusableData, FocusableOptions } from '../focusable';
export {
	blur,
	DEFAULT_FOCUS_BG,
	DEFAULT_FOCUS_FG,
	Focusable,
	focus,
	focusNext,
	focusPrev,
	getFocusable,
	getFocusedEntity,
	getTabIndex,
	getTabOrder,
	hasFocusable,
	isFocusable,
	isFocused,
	isInTabOrder,
	makeFocusable,
	resetFocusState,
	setFocusable,
	setTabIndex,
} from '../focusable';

// Input components
export type {
	InputBufferData,
	KeyboardInputData,
	KeyboardInputOptions,
	MouseInputData,
	MouseInputOptions,
} from '../input';
export {
	clearInputBufferSelection,
	clearKeyboardInput,
	clearMouseInput,
	getInputBuffer,
	getInputBufferText,
	getKeyboardInput,
	getMouseInput,
	hasInputBuffer,
	hasKeyboardInput,
	hasMouseInput,
	InputBuffer,
	inputBufferStore,
	KeyboardInput,
	ModifierFlags,
	MouseButtons,
	MouseInput,
	packModifiers,
	recordClick,
	removeInputBuffer,
	removeKeyboardInput,
	removeMouseInput,
	setInputBuffer,
	setInputBufferSelection,
	setInputBufferText,
	setKeyboardInput,
	setMouseInput,
	unpackModifiers,
} from '../input';

// Interactive component
export type { InteractiveData, InteractiveOptions } from '../interactive';
export { DEFAULT_HOVER_BG, DEFAULT_HOVER_FG, Interactive } from '../interactive';

// TextInput component
export type {
	CursorConfig,
	CursorConfigOptions,
	CursorModeType,
	TextInputAction,
	TextInputConfig,
	TextInputConfigOptions,
	TextInputEvent,
	TextInputState,
	TextInputStore,
} from '../textInput';
export {
	attachTextInputBehavior,
	blurTextInput,
	CursorMode,
	clearSelection,
	clearTextInputCallbacks,
	clearTextInputError,
	DEFAULT_CENSOR_CHAR,
	DEFAULT_CURSOR_BLINK_MS,
	DEFAULT_CURSOR_BLOCK_CHAR,
	DEFAULT_CURSOR_LINE_CHAR,
	DEFAULT_PLACEHOLDER,
	disableTextInput,
	emitCancel,
	emitSubmit,
	emitValueChange,
	enableTextInput,
	endEditingTextInput,
	focusTextInput,
	getCensorChar,
	getCursorChar,
	getCursorConfig,
	getCursorDisplayText,
	getCursorMode,
	getCursorPos,
	getMaxLength,
	getNormalizedSelection,
	getPlaceholder,
	getSelection,
	getTextInputConfig,
	getTextInputState,
	handleTextInputKeyPress,
	hasSelection,
	isCursorBlinkEnabled,
	isCursorVisible,
	isMultiline,
	isSecretMode,
	isTextInput,
	isTextInputDisabled,
	isTextInputEditing,
	isTextInputError,
	isTextInputFocused,
	isTextInputInState,
	maskValue,
	moveCursor,
	onTextInputCancel,
	onTextInputChange,
	onTextInputSubmit,
	resetCursorBlink,
	resetTextInputStore,
	sendTextInputEvent,
	setCursorBlinkEnabled,
	setCursorConfig,
	setCursorMode,
	setCursorPos,
	setSelection,
	setTextInputConfig,
	setTextInputError,
	startEditingTextInput,
	TEXT_INPUT_STATE_MACHINE_CONFIG,
	textInputStore,
	toggleCursorMode,
} from '../textInput';
