/**
 * ECS Components for blECSd
 * @module components
 */

// Animation component
export type {
	AnimationData,
	AnimationDefinition,
	AnimationFrame,
	AnimationOptions,
	PlayAnimationOptions,
} from './animation';
export {
	Animation,
	AnimationDirection,
	animationStore,
	getAnimation,
	getAnimationByName,
	getAnimationData,
	getAnimationIdByName,
	getEntityAnimation,
	hasAnimation,
	isAnimationPlaying,
	pauseAnimation,
	playAnimation,
	playAnimationByName,
	registerAnimation,
	removeAnimation,
	resetAnimationStore,
	resumeAnimation,
	setAnimationDirection,
	setAnimationLoop,
	setAnimationSpeed,
	stopAnimation,
	unregisterAnimation,
	updateAnimationEntity,
} from './animation';
// Border component
export type { BorderCharset, BorderData, BorderOptions } from './border';
export {
	BORDER_ASCII,
	BORDER_BOLD,
	BORDER_DOUBLE,
	BORDER_ROUNDED,
	BORDER_SINGLE,
	Border,
	BorderType,
	DEFAULT_BORDER_BG,
	DEFAULT_BORDER_FG,
	disableAllBorders,
	enableAllBorders,
	getBorder,
	getBorderChar,
	hasBorder,
	hasBorderVisible,
	setBorder,
	setBorderChars,
} from './border';
// Button component
export type { ButtonEvent, ButtonState, ButtonStore } from './button';
export {
	attachButtonBehavior,
	BUTTON_STATE_MACHINE_CONFIG,
	buttonStore,
	clearButtonCallbacks,
	disableButton,
	enableButton,
	getButtonState,
	handleButtonKeyPress,
	isButton,
	isButtonDisabled,
	isButtonFocused,
	isButtonHovered,
	isButtonInState,
	isButtonPressed,
	onButtonPress,
	pressButton,
	resetButtonStore,
	sendButtonEvent,
} from './button';
// Camera component
export type { CameraBounds, CameraData, CameraOptions } from './camera';
// Checkbox component
export type {
	CheckboxDisplay,
	CheckboxDisplayOptions,
	CheckboxEvent,
	CheckboxState,
	CheckboxStore,
} from './checkbox';
export {
	attachCheckboxBehavior,
	CHECKBOX_STATE_MACHINE_CONFIG,
	checkboxStore,
	checkCheckbox,
	clearCheckboxCallbacks,
	clearCheckboxDisplay,
	DEFAULT_CHECKED_CHAR,
	DEFAULT_UNCHECKED_CHAR,
	disableCheckbox,
	enableCheckbox,
	getCheckboxChar,
	getCheckboxDisplay,
	getCheckboxState,
	handleCheckboxKeyPress,
	isChecked,
	isCheckbox,
	isCheckboxDisabled,
	isCheckboxInState,
	isUnchecked,
	onCheckboxChange,
	resetCheckboxStore,
	sendCheckboxEvent,
	setChecked,
	setCheckboxDisplay,
	toggleCheckbox,
	uncheckCheckbox,
} from './checkbox';
export {
	Camera,
	centerCameraOn,
	clearCameraBounds,
	DEFAULT_VIEWPORT_HEIGHT,
	DEFAULT_VIEWPORT_WIDTH,
	getCamera,
	getCameraPosition,
	getCameraTarget,
	hasCamera,
	isAreaInView,
	isCameraBounded,
	isFollowingTarget,
	isInView,
	moveCameraBy,
	removeCamera,
	screenToWorld,
	setCamera,
	setCameraBounds,
	setCameraDeadZone,
	setCameraPosition,
	setCameraTarget,
	updateCameraFollow,
	worldToScreen,
} from './camera';
// Collision component
export type { AABB, ColliderData, ColliderOptions, CollisionPair } from './collision';
export {
	Collider,
	ColliderType,
	canLayersCollide,
	collisionPairKey,
	createCollisionPair,
	DEFAULT_LAYER,
	DEFAULT_MASK,
	getCollider,
	getColliderAABB,
	hasCollider,
	isTrigger,
	removeCollider,
	setCollider,
	setCollisionLayer,
	setCollisionMask,
	setTrigger,
	testAABBOverlap,
	testCircleAABBOverlap,
	testCircleOverlap,
	testCollision,
} from './collision';
// Content component
export type { ContentData, ContentOptions } from './content';
export {
	appendContent,
	Content,
	clearContent,
	contentStore,
	getContent,
	getContentData,
	getContentHash,
	getContentLength,
	getText,
	hasContent,
	isParsingTags,
	isTextWrapped,
	resetContentStore,
	setContent,
	setParseTags,
	setText,
	setTextAlign,
	setTextVAlign,
	setTextWrap,
	TextAlign,
	TextVAlign,
} from './content';
// Dimensions component
export type { DimensionConstraints, DimensionsData, DimensionValue } from './dimensions';
export {
	AUTO_DIMENSION,
	Dimensions,
	decodePercentage,
	encodePercentage,
	getDimensions,
	getResolvedHeight,
	getResolvedWidth,
	hasDimensions,
	isPercentage,
	setConstraints,
	setDimensions,
	setShrink,
	shouldShrink,
} from './dimensions';
// Focusable component
export type { FocusableData, FocusableOptions } from './focusable';
export {
	blur,
	DEFAULT_FOCUS_BG,
	DEFAULT_FOCUS_FG,
	Focusable,
	focus,
	focusNext,
	focusPrev,
	getFocusable,
	getFocusedEntity,
	getTabIndex,
	getTabOrder,
	hasFocusable,
	isFocusable,
	isFocused,
	isInTabOrder,
	makeFocusable,
	resetFocusState,
	setFocusable,
	setTabIndex,
} from './focusable';
// Form component
export type {
	FormFieldValue,
	FormResetCallback,
	FormStore,
	FormSubmitCallback,
	FormValues,
} from './form';
export {
	attachFormBehavior,
	autoRegisterFields,
	clearFormCallbacks,
	focusNextField,
	focusPrevField,
	formStore,
	getFieldName,
	getFieldValue,
	getFormFields,
	getFormTabOrder,
	getFormValues,
	handleFormKeyPress,
	isForm,
	isFormKeysEnabled,
	isFormSubmitOnEnter,
	onFormReset,
	onFormSubmit,
	registerFormField,
	resetForm,
	resetFormStore,
	setFieldValue,
	submitForm,
	unregisterFormField,
} from './form';
// Hierarchy component
export type { HierarchyData } from './hierarchy';
export {
	appendChild,
	detach,
	getAncestors,
	getChildAt,
	getChildIndex,
	getChildren,
	getDepth,
	getDescendants,
	getFirstChild,
	getHierarchy,
	getLastChild,
	getNextSibling,
	getParent,
	getPrevSibling,
	Hierarchy,
	hasHierarchy,
	insertAfter,
	insertAt,
	insertBefore,
	isLeaf,
	isRoot,
	NULL_ENTITY,
	prepend,
	removeChild,
	setParent,
} from './hierarchy';
// Input components
export type {
	InputBufferData,
	KeyboardInputData,
	KeyboardInputOptions,
	MouseInputData,
	MouseInputOptions,
} from './input';
export {
	clearInputBufferSelection,
	clearKeyboardInput,
	clearMouseInput,
	getInputBuffer,
	getInputBufferText,
	getKeyboardInput,
	getMouseInput,
	hasInputBuffer,
	hasKeyboardInput,
	hasMouseInput,
	InputBuffer,
	inputBufferStore,
	KeyboardInput,
	ModifierFlags,
	MouseButtons,
	MouseInput,
	packModifiers,
	recordClick,
	removeInputBuffer,
	removeKeyboardInput,
	removeMouseInput,
	setInputBuffer,
	setInputBufferSelection,
	setInputBufferText,
	setKeyboardInput,
	setMouseInput,
	unpackModifiers,
} from './input';
// Interactive component
export type { InteractiveData, InteractiveOptions } from './interactive';
export {
	clearInteractionState,
	DEFAULT_HOVER_BG,
	DEFAULT_HOVER_FG,
	getInteractive,
	hasInteractive,
	Interactive,
	isClickable,
	isDraggable,
	isHoverable,
	isHovered,
	isKeyable,
	isPressed,
	setClickable,
	setDraggable,
	setHoverable,
	setHovered,
	setInteractive,
	setKeyable,
	setPressed,
} from './interactive';
// Label component
export type { LabelData, LabelOptions } from './label';
export {
	getLabel,
	getLabelPosition,
	getLabelText,
	hasLabel,
	hasLabelText,
	Label,
	LabelPosition,
	labelStore,
	removeLabel,
	resetLabelStore,
	setLabel,
	setLabelOffset,
	setLabelPosition,
} from './label';
// Padding component
export type { PaddingData, PaddingOptions } from './padding';
export {
	getHorizontalPadding,
	getPadding,
	getVerticalPadding,
	hasPadding,
	hasPaddingValue,
	Padding,
	setPadding,
	setPaddingAll,
	setPaddingHV,
} from './padding';
// Position component
export type { PositionData } from './position';
// RadioButton component
export type {
	RadioButtonDisplay,
	RadioButtonDisplayOptions,
	RadioButtonEvent,
	RadioButtonState,
	RadioButtonStore,
	RadioSelectCallback,
	RadioSetStore,
} from './radioButton';
export {
	attachRadioButtonBehavior,
	attachRadioSetBehavior,
	clearRadioButtonDisplay,
	clearRadioSetCallbacks,
	DEFAULT_RADIO_SELECTED_CHAR,
	DEFAULT_RADIO_UNSELECTED_CHAR,
	deselectRadioButton,
	disableRadioButton,
	enableRadioButton,
	getRadioButtonChar,
	getRadioButtonDisplay,
	getRadioButtonsInSet,
	getRadioButtonState,
	getRadioSet,
	getRadioValue,
	getSelectedButton,
	getSelectedValue,
	handleRadioButtonKeyPress,
	isRadioButton,
	isRadioButtonDisabled,
	isRadioButtonInState,
	isRadioSelected,
	isRadioSet,
	onRadioSelect,
	RADIO_BUTTON_STATE_MACHINE_CONFIG,
	radioButtonStore,
	radioSetStore,
	resetRadioButtonStore,
	selectRadioButton,
	selectRadioByValue,
	sendRadioButtonEvent,
	setRadioButtonDisplay,
	setRadioSet,
	setRadioValue,
} from './radioButton';
// ProgressBar component
export type {
	ProgressBarDisplay,
	ProgressBarDisplayOptions,
	ProgressBarStore,
	ProgressChangeCallback,
	ProgressCompleteCallback,
} from './progressBar';
export {
	attachProgressBarBehavior,
	clearProgressBarCallbacks,
	clearProgressBarDisplay,
	completeProgress,
	decrementProgress,
	DEFAULT_EMPTY_CHAR,
	DEFAULT_EMPTY_CHAR_VERTICAL,
	DEFAULT_FILL_CHAR,
	DEFAULT_FILL_CHAR_VERTICAL,
	getProgress,
	getProgressBarDisplay,
	getProgressEmptyChar,
	getProgressFillChar,
	getProgressMax,
	getProgressMin,
	getProgressOrientation,
	getProgressPercentage,
	incrementProgress,
	isProgressBar,
	isProgressComplete,
	isShowingPercentage,
	onProgressChange,
	onProgressComplete,
	progressBarStore,
	ProgressOrientation,
	renderProgressString,
	resetProgress,
	resetProgressBarStore,
	setProgress,
	setProgressBarDisplay,
	setProgressOrientation,
	setProgressRange,
	setShowPercentage,
} from './progressBar';
export {
	getPosition,
	hasPosition,
	isAbsolute,
	moveBy,
	Position,
	setAbsolute,
	setPosition,
	setZIndex,
} from './position';
// Renderable component
export type { RenderableData, StyleData, StyleOptions } from './renderable';
export {
	colorToHex,
	DEFAULT_BG,
	DEFAULT_FG,
	getRenderable,
	getStyle,
	hasRenderable,
	hexToColor,
	hide,
	isDetached,
	isDirty,
	isEffectivelyVisible,
	isVisible,
	markClean,
	markDirty,
	packColor,
	Renderable,
	setStyle,
	setVisible,
	show,
	toggle,
	unpackColor,
} from './renderable';
// Scrollable component
export type {
	ScrollableData,
	ScrollableOptions,
	ScrollPercentage,
	ScrollPosition,
} from './scrollable';
export {
	canScroll,
	getScroll,
	getScrollable,
	getScrollPercentage,
	hasScrollable,
	isAtBottom,
	isAtTop,
	Scrollable,
	ScrollbarVisibility,
	scrollBy,
	scrollTo,
	scrollToBottom,
	scrollToTop,
	setScroll,
	setScrollable,
	setScrollbarVisibility,
	setScrollSize,
} from './scrollable';
// Sprite component
export type {
	SpriteCell,
	SpriteData,
	SpriteFrame,
	SpriteSheetData,
	SpriteSheetOptions,
} from './sprite';
export {
	getCurrentFrame,
	getEntitySpriteSheet,
	getSprite,
	getSpriteIdByName,
	getSpriteSheet,
	getSpriteSheetByName,
	hasSprite,
	nextFrame,
	prevFrame,
	registerSprite,
	removeSprite,
	resetSpriteStore,
	Sprite,
	setFrame,
	setSprite,
	setSpriteByName,
	spriteStore,
	unregisterSprite,
} from './sprite';
// State Machine component
export {
	attachStateMachine,
	canSendEvent,
	detachStateMachine,
	getPreviousState,
	getState,
	getStateAge,
	hasStateMachine,
	isInState,
	StateMachineStore,
	sendEvent,
	updateStateAge,
} from './stateMachine';
// TextInput component
export type {
	CursorConfig,
	CursorConfigOptions,
	CursorModeType,
	TextInputAction,
	TextInputConfig,
	TextInputConfigOptions,
	TextInputEvent,
	TextInputState,
	TextInputStore,
} from './textInput';
export {
	attachTextInputBehavior,
	blurTextInput,
	clearSelection,
	clearTextInputCallbacks,
	clearTextInputError,
	CursorMode,
	DEFAULT_CENSOR_CHAR,
	DEFAULT_CURSOR_BLINK_MS,
	DEFAULT_CURSOR_BLOCK_CHAR,
	DEFAULT_CURSOR_LINE_CHAR,
	DEFAULT_PLACEHOLDER,
	disableTextInput,
	emitCancel,
	emitSubmit,
	emitValueChange,
	enableTextInput,
	endEditingTextInput,
	focusTextInput,
	getCensorChar,
	getCursorChar,
	getCursorConfig,
	getCursorDisplayText,
	getCursorMode,
	getCursorPos,
	getMaxLength,
	getNormalizedSelection,
	getPlaceholder,
	getSelection,
	getTextInputConfig,
	getTextInputState,
	handleTextInputKeyPress,
	hasSelection,
	isCursorBlinkEnabled,
	isCursorVisible,
	isMultiline,
	isSecretMode,
	isTextInput,
	isTextInputDisabled,
	isTextInputEditing,
	isTextInputError,
	isTextInputFocused,
	isTextInputInState,
	maskValue,
	moveCursor,
	onTextInputCancel,
	onTextInputChange,
	onTextInputSubmit,
	resetCursorBlink,
	resetTextInputStore,
	sendTextInputEvent,
	setCursorBlinkEnabled,
	setCursorConfig,
	setCursorMode,
	setCursorPos,
	setSelection,
	setTextInputConfig,
	setTextInputError,
	startEditingTextInput,
	TEXT_INPUT_STATE_MACHINE_CONFIG,
	textInputStore,
	toggleCursorMode,
} from './textInput';
// Velocity and Acceleration components
export type { AccelerationData, VelocityData, VelocityOptions } from './velocity';
export {
	Acceleration,
	addVelocity,
	applyAccelerationToEntity,
	applyFrictionToEntity,
	applyVelocityToEntity,
	clampSpeedForEntity,
	clearAcceleration,
	getAcceleration,
	getSpeed,
	getVelocity,
	hasAcceleration,
	hasVelocity,
	removeAcceleration,
	removeVelocity,
	setAcceleration,
	setFriction,
	setMaxSpeed,
	setVelocity,
	setVelocityOptions,
	stopEntity,
	updateEntityMovement,
	Velocity,
} from './velocity';
