/**
 * ECS Components for blECSd
 * @module components
 */

// Animation component
export type {
	AnimationData,
	AnimationDefinition,
	AnimationFrame,
	AnimationOptions,
	PlayAnimationOptions,
} from './animation';
export {
	Animation,
	AnimationDirection,
	animationStore,
	getAnimation,
	getAnimationByName,
	getAnimationData,
	getAnimationIdByName,
	getEntityAnimation,
	hasAnimation,
	isAnimationPlaying,
	pauseAnimation,
	playAnimation,
	playAnimationByName,
	registerAnimation,
	removeAnimation,
	resetAnimationStore,
	resumeAnimation,
	setAnimationDirection,
	setAnimationLoop,
	setAnimationSpeed,
	stopAnimation,
	unregisterAnimation,
	updateAnimationEntity,
} from './animation';
// Border component
export type { BorderCharset, BorderData, BorderOptions } from './border';
export {
	BORDER_ASCII,
	BORDER_BOLD,
	BORDER_DOUBLE,
	BORDER_ROUNDED,
	BORDER_SINGLE,
	Border,
	BorderType,
	DEFAULT_BORDER_BG,
	DEFAULT_BORDER_FG,
	disableAllBorders,
	enableAllBorders,
	getBorder,
	getBorderChar,
	hasBorder,
	hasBorderVisible,
	setBorder,
	setBorderChars,
} from './border';
// Button component
export type { ButtonEvent, ButtonState, ButtonStore } from './button';
export {
	attachButtonBehavior,
	BUTTON_STATE_MACHINE_CONFIG,
	buttonStore,
	clearButtonCallbacks,
	disableButton,
	enableButton,
	getButtonState,
	handleButtonKeyPress,
	isButton,
	isButtonDisabled,
	isButtonFocused,
	isButtonHovered,
	isButtonInState,
	isButtonPressed,
	onButtonPress,
	pressButton,
	resetButtonStore,
	sendButtonEvent,
} from './button';
// Camera component
export type { CameraBounds, CameraData, CameraOptions } from './camera';
export {
	Camera,
	centerCameraOn,
	clearCameraBounds,
	DEFAULT_VIEWPORT_HEIGHT,
	DEFAULT_VIEWPORT_WIDTH,
	getCamera,
	getCameraPosition,
	getCameraTarget,
	hasCamera,
	isAreaInView,
	isCameraBounded,
	isFollowingTarget,
	isInView,
	moveCameraBy,
	removeCamera,
	screenToWorld,
	setCamera,
	setCameraBounds,
	setCameraDeadZone,
	setCameraPosition,
	setCameraTarget,
	updateCameraFollow,
	worldToScreen,
} from './camera';
// Checkbox component
export type {
	CheckboxDisplay,
	CheckboxDisplayOptions,
	CheckboxEvent,
	CheckboxState,
	CheckboxStore,
} from './checkbox';
export {
	attachCheckboxBehavior,
	CHECKBOX_STATE_MACHINE_CONFIG,
	checkboxStore,
	checkCheckbox,
	clearCheckboxCallbacks,
	clearCheckboxDisplay,
	DEFAULT_CHECKED_CHAR,
	DEFAULT_UNCHECKED_CHAR,
	disableCheckbox,
	enableCheckbox,
	getCheckboxChar,
	getCheckboxDisplay,
	getCheckboxState,
	handleCheckboxKeyPress,
	isCheckbox,
	isCheckboxDisabled,
	isCheckboxInState,
	isChecked,
	isUnchecked,
	onCheckboxChange,
	resetCheckboxStore,
	sendCheckboxEvent,
	setCheckboxDisplay,
	setChecked,
	toggleCheckbox,
	uncheckCheckbox,
} from './checkbox';
// Collision component
export type { AABB, ColliderData, ColliderOptions, CollisionPair } from './collision';
export {
	Collider,
	ColliderType,
	canLayersCollide,
	collisionPairKey,
	createCollisionPair,
	DEFAULT_LAYER,
	DEFAULT_MASK,
	getCollider,
	getColliderAABB,
	hasCollider,
	isTrigger,
	removeCollider,
	setCollider,
	setCollisionLayer,
	setCollisionMask,
	setTrigger,
	testAABBOverlap,
	testCircleAABBOverlap,
	testCircleOverlap,
	testCollision,
} from './collision';
// Content component
export type { ContentData, ContentOptions } from './content';
export {
	appendContent,
	Content,
	clearContent,
	contentStore,
	getContent,
	getContentData,
	getContentHash,
	getContentLength,
	getText,
	hasContent,
	isParsingTags,
	isTextWrapped,
	resetContentStore,
	setContent,
	setParseTags,
	setText,
	setTextAlign,
	setTextVAlign,
	setTextWrap,
	TextAlign,
	TextVAlign,
} from './content';
// Dimensions component
export type { DimensionConstraints, DimensionsData, DimensionValue } from './dimensions';
export {
	AUTO_DIMENSION,
	Dimensions,
	decodePercentage,
	encodePercentage,
	getDimensions,
	getResolvedHeight,
	getResolvedWidth,
	hasDimensions,
	isPercentage,
	setConstraints,
	setDimensions,
	setShrink,
	shouldShrink,
} from './dimensions';
// Focusable component
export type { FocusableData, FocusableOptions } from './focusable';
export {
	blur,
	DEFAULT_FOCUS_BG,
	DEFAULT_FOCUS_FG,
	Focusable,
	focus,
	focusNext,
	focusPrev,
	getFocusable,
	getFocusedEntity,
	getTabIndex,
	getTabOrder,
	hasFocusable,
	isFocusable,
	isFocused,
	isInTabOrder,
	makeFocusable,
	resetFocusState,
	setFocusable,
	setTabIndex,
} from './focusable';
// Form component
export type {
	FormFieldValue,
	FormResetCallback,
	FormStore,
	FormSubmitCallback,
	FormValues,
} from './form';
export {
	attachFormBehavior,
	autoRegisterFields,
	clearFormCallbacks,
	focusNextField,
	focusPrevField,
	formStore,
	getFieldName,
	getFieldValue,
	getFormFields,
	getFormTabOrder,
	getFormValues,
	handleFormKeyPress,
	isForm,
	isFormKeysEnabled,
	isFormSubmitOnEnter,
	onFormReset,
	onFormSubmit,
	registerFormField,
	resetForm,
	resetFormStore,
	setFieldValue,
	submitForm,
	unregisterFormField,
} from './form';
// Hierarchy component
export type { HierarchyData, TraversalCallback } from './hierarchy';
export {
	appendChild,
	detach,
	forAncestors,
	forDescendants,
	getAncestors,
	getChildAt,
	getChildIndex,
	getChildren,
	getCommonAncestor,
	getDepth,
	getDescendants,
	getFirstChild,
	getHierarchy,
	getLastChild,
	getNextSibling,
	getParent,
	getPrevSibling,
	getRoot,
	getSiblings,
	Hierarchy,
	hasAncestor,
	hasDescendant,
	hasHierarchy,
	insertAfter,
	insertAt,
	insertBefore,
	isLeaf,
	isRoot,
	NULL_ENTITY,
	prepend,
	removeChild,
	setParent,
} from './hierarchy';
// Input components
export type {
	InputBufferData,
	KeyboardInputData,
	KeyboardInputOptions,
	MouseInputData,
	MouseInputOptions,
} from './input';
export {
	clearInputBufferSelection,
	clearKeyboardInput,
	clearMouseInput,
	getInputBuffer,
	getInputBufferText,
	getKeyboardInput,
	getMouseInput,
	hasInputBuffer,
	hasKeyboardInput,
	hasMouseInput,
	InputBuffer,
	inputBufferStore,
	KeyboardInput,
	ModifierFlags,
	MouseButtons,
	MouseInput,
	packModifiers,
	recordClick,
	removeInputBuffer,
	removeKeyboardInput,
	removeMouseInput,
	setInputBuffer,
	setInputBufferSelection,
	setInputBufferText,
	setKeyboardInput,
	setMouseInput,
	unpackModifiers,
} from './input';
// Interactive component
export type { InteractiveData, InteractiveOptions } from './interactive';
export {
	clearInteractionState,
	DEFAULT_HOVER_BG,
	DEFAULT_HOVER_FG,
	getInteractive,
	hasInteractive,
	Interactive,
	isClickable,
	isDraggable,
	isHoverable,
	isHovered,
	isKeyable,
	isPressed,
	setClickable,
	setDraggable,
	setHoverable,
	setHovered,
	setInteractive,
	setKeyable,
	setPressed,
} from './interactive';
// Label component
export type { LabelData, LabelOptions } from './label';
export {
	getLabel,
	getLabelPosition,
	getLabelText,
	hasLabel,
	hasLabelText,
	Label,
	LabelPosition,
	labelStore,
	removeLabel,
	resetLabelStore,
	setLabel,
	setLabelOffset,
	setLabelPosition,
} from './label';
// List component
export type {
	ListAction,
	ListDisplay,
	ListDisplayOptions,
	ListEvent,
	ListItem,
	ListLazyLoadCallback,
	ListScrollCallback,
	ListScrollInfo,
	ListSelectCallback,
	ListState,
	ListStore,
} from './list';
export {
	activateSelected,
	addItem,
	// Virtualization exports
	appendItems,
	appendToSearchQuery,
	attachListBehavior,
	backspaceSearchQuery,
	blurList,
	checkNeedsLoad,
	clearItems,
	clearLazyLoadCallback,
	clearListCallbacks,
	clearListDisplay,
	clearSearchQuery,
	clearSelection as clearListSelection,
	DEFAULT_DISABLED_FG,
	DEFAULT_ITEM_BG,
	DEFAULT_ITEM_FG,
	DEFAULT_SELECTED_BG,
	DEFAULT_SELECTED_FG,
	DEFAULT_SELECTED_PREFIX,
	DEFAULT_UNSELECTED_PREFIX,
	disableList,
	enableList,
	endListSearch,
	ensureVisible,
	findAndSelectByText,
	findNextMatch,
	focusList,
	getFirstVisible,
	getItem,
	getItemCount,
	getItems,
	getLazyLoadCallback,
	getListDisplay,
	getListSearchQuery,
	getListState,
	getLoadingPlaceholder,
	getScrollInfo,
	getSelectedIndex as getListSelectedIndex,
	getSelectedItem,
	getTotalCount,
	getVisibleCount,
	getVisibleItems,
	handleListKeyPress,
	isList,
	isListDisabled,
	isListFocused,
	isListInState,
	isListInteractive,
	isListKeysEnabled,
	isListLoading,
	isListMouseEnabled,
	isListSearchEnabled,
	isListSearching,
	LIST_STATE_MACHINE_CONFIG,
	listStore,
	loadItems,
	onListActivate,
	onListScroll,
	onListSearchChange,
	onListSelect,
	removeItem,
	renderListItems,
	resetListStore,
	scrollPage,
	selectByValue,
	selectFirst,
	selectLast,
	selectNext,
	selectPrev,
	sendListEvent,
	setFirstVisible,
	setItems,
	setLazyLoadCallback,
	setListDisplay,
	setListInteractive,
	setListKeys,
	setListLoading,
	setListMouse,
	setListSearchEnabled,
	setListSearchQuery,
	setLoadingPlaceholder,
	setSelectedIndex as setListSelectedIndex,
	setTotalCount,
	setVisibleCount,
	startListSearch,
	updateItem,
} from './list';
// Padding component
export type { PaddingData, PaddingOptions } from './padding';
export {
	getHorizontalPadding,
	getPadding,
	getVerticalPadding,
	hasPadding,
	hasPaddingValue,
	Padding,
	setPadding,
	setPaddingAll,
	setPaddingHV,
} from './padding';
// Position component
export type { PositionData } from './position';
export {
	bringToFront,
	getPosition,
	getZIndex,
	hasPosition,
	isAbsolute,
	moveBackward,
	moveBy,
	moveForward,
	normalizeZIndices,
	Position,
	sendToBack,
	setAbsolute,
	setPosition,
	setZIndex,
	swapZIndex,
} from './position';
// ProgressBar component
export type {
	ProgressBarDisplay,
	ProgressBarDisplayOptions,
	ProgressBarStore,
	ProgressChangeCallback,
	ProgressCompleteCallback,
} from './progressBar';
export {
	attachProgressBarBehavior,
	clearProgressBarCallbacks,
	clearProgressBarDisplay,
	completeProgress,
	DEFAULT_EMPTY_CHAR,
	DEFAULT_EMPTY_CHAR_VERTICAL,
	DEFAULT_FILL_CHAR,
	DEFAULT_FILL_CHAR_VERTICAL,
	decrementProgress,
	getProgress,
	getProgressBarDisplay,
	getProgressEmptyChar,
	getProgressFillChar,
	getProgressMax,
	getProgressMin,
	getProgressOrientation,
	getProgressPercentage,
	incrementProgress,
	isProgressBar,
	isProgressComplete,
	isShowingPercentage,
	onProgressChange,
	onProgressComplete,
	ProgressOrientation,
	progressBarStore,
	renderProgressString,
	resetProgress,
	resetProgressBarStore,
	setProgress,
	setProgressBarDisplay,
	setProgressOrientation,
	setProgressRange,
	setShowPercentage,
} from './progressBar';
// RadioButton component
export type {
	RadioButtonDisplay,
	RadioButtonDisplayOptions,
	RadioButtonEvent,
	RadioButtonState,
	RadioButtonStore,
	RadioSelectCallback,
	RadioSetStore,
} from './radioButton';
export {
	attachRadioButtonBehavior,
	attachRadioSetBehavior,
	clearRadioButtonDisplay,
	clearRadioSetCallbacks,
	DEFAULT_RADIO_SELECTED_CHAR,
	DEFAULT_RADIO_UNSELECTED_CHAR,
	deselectRadioButton,
	disableRadioButton,
	enableRadioButton,
	getRadioButtonChar,
	getRadioButtonDisplay,
	getRadioButtonState,
	getRadioButtonsInSet,
	getRadioSet,
	getRadioValue,
	getSelectedButton,
	getSelectedValue,
	handleRadioButtonKeyPress,
	isRadioButton,
	isRadioButtonDisabled,
	isRadioButtonInState,
	isRadioSelected,
	isRadioSet,
	onRadioSelect,
	RADIO_BUTTON_STATE_MACHINE_CONFIG,
	radioButtonStore,
	radioSetStore,
	resetRadioButtonStore,
	selectRadioButton,
	selectRadioByValue,
	sendRadioButtonEvent,
	setRadioButtonDisplay,
	setRadioSet,
	setRadioValue,
} from './radioButton';
// Renderable component
export type { RenderableData, StyleData, StyleOptions } from './renderable';
export {
	colorToHex,
	DEFAULT_BG,
	DEFAULT_FG,
	getRenderable,
	getStyle,
	hasRenderable,
	hexToColor,
	hide,
	isDetached,
	isDirty,
	isEffectivelyVisible,
	isVisible,
	markClean,
	markDirty,
	packColor,
	Renderable,
	setStyle,
	setVisible,
	show,
	toggle,
	unpackColor,
} from './renderable';
// Scrollable component
export type {
	ScrollableData,
	ScrollableOptions,
	ScrollPercentage,
	ScrollPosition,
} from './scrollable';
export {
	canScroll,
	getScroll,
	getScrollable,
	getScrollPercentage,
	hasScrollable,
	isAtBottom,
	isAtTop,
	Scrollable,
	ScrollbarVisibility,
	scrollBy,
	scrollTo,
	scrollToBottom,
	scrollToTop,
	setScroll,
	setScrollable,
	setScrollbarVisibility,
	setScrollSize,
} from './scrollable';
// Select component
export type {
	SelectAction,
	SelectCallback,
	SelectDisplay,
	SelectDisplayOptions,
	SelectEvent,
	SelectOption,
	SelectState,
	SelectStore,
} from './select';
export {
	attachSelectBehavior,
	clearSelectCallbacks,
	clearSelectDisplay,
	clearSelection as clearSelectSelection,
	closeSelect,
	DEFAULT_CLOSED_INDICATOR,
	DEFAULT_OPEN_INDICATOR,
	DEFAULT_SELECTED_MARK,
	DEFAULT_SEPARATOR,
	disableSelect,
	enableSelect,
	getHighlightedIndex,
	getOptionAt,
	getOptionCount,
	getSelectDisplay,
	getSelectedIndex,
	getSelectedLabel,
	getSelectedOption,
	getSelectedValue as getSelectValue,
	getSelectIndicator,
	getSelectOptions,
	getSelectState,
	handleSelectKeyPress,
	highlightNext,
	highlightPrev,
	isSelect,
	isSelectDisabled,
	isSelectInState,
	isSelectOpen,
	onSelectChange,
	onSelectClose,
	onSelectOpen,
	openSelect,
	resetSelectStore,
	SELECT_STATE_MACHINE_CONFIG,
	selectHighlighted,
	selectOptionByIndex,
	selectOptionByValue,
	selectStore,
	sendSelectEvent,
	setHighlightedIndex,
	setSelectDisplay,
	setSelectOptions,
	toggleSelect,
} from './select';
// Slider component
export type {
	SliderAction,
	SliderChangeCallback,
	SliderDisplay,
	SliderDisplayOptions,
	SliderEvent,
	SliderOrientationType,
	SliderState,
	SliderStore,
} from './slider';
export {
	attachSliderBehavior,
	blurSlider,
	clearSliderCallbacks,
	clearSliderDisplay,
	DEFAULT_FILL_BG as DEFAULT_SLIDER_FILL_BG,
	DEFAULT_FILL_CHAR as DEFAULT_SLIDER_FILL_CHAR,
	DEFAULT_FILL_CHAR_VERTICAL as DEFAULT_SLIDER_FILL_CHAR_VERTICAL,
	DEFAULT_FILL_FG as DEFAULT_SLIDER_FILL_FG,
	DEFAULT_THUMB_BG,
	DEFAULT_THUMB_CHAR,
	DEFAULT_THUMB_FG,
	DEFAULT_TRACK_BG,
	DEFAULT_TRACK_CHAR,
	DEFAULT_TRACK_CHAR_VERTICAL,
	DEFAULT_TRACK_FG,
	decrementSlider,
	disableSlider,
	enableSlider,
	focusSlider,
	getSliderDisplay,
	getSliderMax,
	getSliderMin,
	getSliderOrientation,
	getSliderPercentage,
	getSliderState,
	getSliderStep,
	getSliderValue,
	handleSliderKeyPress,
	incrementSlider,
	isShowingSliderValue,
	isSlider,
	isSliderDisabled,
	isSliderDragging,
	isSliderFocused,
	isSliderHorizontal,
	isSliderInState,
	isSliderVertical,
	onSliderChange,
	onSliderDragEnd,
	onSliderDragStart,
	renderSliderString,
	resetSliderStore,
	SLIDER_STATE_MACHINE_CONFIG,
	SliderOrientation,
	sendSliderEvent,
	setShowSliderValue,
	setSliderDisplay,
	setSliderFromPercentage,
	setSliderOrientation,
	setSliderRange,
	setSliderStep,
	setSliderToMax,
	setSliderToMin,
	setSliderValue,
	sliderStore,
	startDragging,
	stopDragging,
} from './slider';
// Sprite component
export type {
	SpriteCell,
	SpriteData,
	SpriteFrame,
	SpriteSheetData,
	SpriteSheetOptions,
} from './sprite';
export {
	getCurrentFrame,
	getEntitySpriteSheet,
	getSprite,
	getSpriteIdByName,
	getSpriteSheet,
	getSpriteSheetByName,
	hasSprite,
	nextFrame,
	prevFrame,
	registerSprite,
	removeSprite,
	resetSpriteStore,
	Sprite,
	setFrame,
	setSprite,
	setSpriteByName,
	spriteStore,
	unregisterSprite,
} from './sprite';
// State Machine component
export {
	attachStateMachine,
	canSendEvent,
	detachStateMachine,
	getPreviousState,
	getState,
	getStateAge,
	hasStateMachine,
	isInState,
	StateMachineStore,
	sendEvent,
	updateStateAge,
} from './stateMachine';
// Table component
export type {
	CellAlign,
	TableCell,
	TableColumn,
	TableData,
	TableDisplay,
	TableDisplayOptions,
	TableRow,
	TableStore,
} from './table';
export {
	appendRow,
	attachTableBehavior,
	calculateColumnWidths,
	clearData,
	clearTableDisplay,
	DEFAULT_BORDER_BG as DEFAULT_TABLE_BORDER_BG,
	DEFAULT_BORDER_FG as DEFAULT_TABLE_BORDER_FG,
	DEFAULT_CELL_BG,
	DEFAULT_CELL_FG,
	DEFAULT_HEADER_BG,
	DEFAULT_HEADER_FG,
	detachTableBehavior,
	getCell,
	getCellPadding,
	getCellValue,
	getColCount,
	getColumn,
	getColumns,
	getData,
	getDataAsStrings,
	getDataRows,
	getHeaderRowCount,
	getHeaderRows,
	getRow,
	getRowCount,
	getTableDisplay,
	hasCellBorders,
	insertRow,
	isTable,
	removeRow,
	renderTableLines,
	resetTableStore,
	setCell,
	setCellBorders,
	setCellPadding,
	setData,
	setHeaderRowCount,
	setHeaders,
	setTableDisplay,
	Table,
	tableStore,
} from './table';
// TextInput component
export type {
	CursorConfig,
	CursorConfigOptions,
	CursorModeType,
	TextInputAction,
	TextInputConfig,
	TextInputConfigOptions,
	TextInputEvent,
	TextInputState,
	TextInputStore,
} from './textInput';
export {
	attachTextInputBehavior,
	blurTextInput,
	CursorMode,
	clearSelection,
	clearTextInputCallbacks,
	clearTextInputError,
	DEFAULT_CENSOR_CHAR,
	DEFAULT_CURSOR_BLINK_MS,
	DEFAULT_CURSOR_BLOCK_CHAR,
	DEFAULT_CURSOR_LINE_CHAR,
	DEFAULT_PLACEHOLDER,
	disableTextInput,
	emitCancel,
	emitSubmit,
	emitValueChange,
	enableTextInput,
	endEditingTextInput,
	focusTextInput,
	getCensorChar,
	getCursorChar,
	getCursorConfig,
	getCursorDisplayText,
	getCursorMode,
	getCursorPos,
	getMaxLength,
	getNormalizedSelection,
	getPlaceholder,
	getSelection,
	getTextInputConfig,
	getTextInputState,
	handleTextInputKeyPress,
	hasSelection,
	isCursorBlinkEnabled,
	isCursorVisible,
	isMultiline,
	isSecretMode,
	isTextInput,
	isTextInputDisabled,
	isTextInputEditing,
	isTextInputError,
	isTextInputFocused,
	isTextInputInState,
	maskValue,
	moveCursor,
	onTextInputCancel,
	onTextInputChange,
	onTextInputSubmit,
	resetCursorBlink,
	resetTextInputStore,
	sendTextInputEvent,
	setCursorBlinkEnabled,
	setCursorConfig,
	setCursorMode,
	setCursorPos,
	setSelection,
	setTextInputConfig,
	setTextInputError,
	startEditingTextInput,
	TEXT_INPUT_STATE_MACHINE_CONFIG,
	textInputStore,
	toggleCursorMode,
} from './textInput';
// Velocity and Acceleration components
export type { AccelerationData, VelocityData, VelocityOptions } from './velocity';
export {
	Acceleration,
	addVelocity,
	applyAccelerationToEntity,
	applyFrictionToEntity,
	applyVelocityToEntity,
	clampSpeedForEntity,
	clearAcceleration,
	getAcceleration,
	getSpeed,
	getVelocity,
	hasAcceleration,
	hasVelocity,
	removeAcceleration,
	removeVelocity,
	setAcceleration,
	setFriction,
	setMaxSpeed,
	setVelocity,
	setVelocityOptions,
	stopEntity,
	updateEntityMovement,
	Velocity,
} from './velocity';
