/**
 * blECSd Terminal Game Library
 *
 * A modern terminal game library built on TypeScript and ECS architecture.
 *
 * @packageDocumentation
 */

// =============================================================================
// VERSION
// =============================================================================
export const VERSION = '0.0.1';

// =============================================================================
// COMPONENTS - ECS Components and Helpers
// =============================================================================
export type {
	BorderCharset,
	BorderData,
	BorderOptions,
	ContentData,
	ContentOptions,
	DimensionConstraints,
	DimensionsData,
	DimensionValue,
	FocusableData,
	FocusableOptions,
	HierarchyData,
	InteractiveData,
	InteractiveOptions,
	LabelData,
	LabelOptions,
	PaddingData,
	PaddingOptions,
	PositionData,
	RenderableData,
	ScrollableData,
	ScrollableOptions,
	ScrollPercentage,
	ScrollPosition,
	StyleData,
	StyleOptions,
} from './components';
export {
	// Dimensions
	AUTO_DIMENSION,
	// Hierarchy
	appendChild,
	appendContent,
	// State Machine
	attachStateMachine,
	BORDER_ASCII,
	BORDER_BOLD,
	BORDER_DOUBLE,
	BORDER_ROUNDED,
	BORDER_SINGLE,
	// Border
	Border,
	BorderType,
	blur,
	Content,
	canScroll,
	canSendEvent,
	clearContent,
	clearInteractionState,
	// Renderable
	colorToHex,
	contentStore,
	DEFAULT_BG,
	DEFAULT_BORDER_BG,
	DEFAULT_BORDER_FG,
	DEFAULT_FG,
	DEFAULT_FOCUS_BG,
	DEFAULT_FOCUS_FG,
	DEFAULT_HOVER_BG,
	DEFAULT_HOVER_FG,
	Dimensions,
	decodePercentage,
	detachStateMachine,
	disableAllBorders,
	enableAllBorders,
	encodePercentage,
	Focusable,
	focus,
	focusNext,
	focusPrev,
	getAncestors,
	getBorder,
	getBorderChar,
	getChildren,
	getContent,
	getContentData,
	getContentHash,
	getContentLength,
	getDepth,
	getDescendants,
	getDimensions,
	getFocusable,
	getFocusedEntity,
	getHierarchy,
	getHorizontalPadding,
	getInteractive,
	// Label
	getLabel,
	getLabelPosition,
	getLabelText,
	getNextSibling,
	getPadding,
	getParent,
	// Position
	getPosition,
	getPreviousState,
	getPrevSibling,
	getRenderable,
	getResolvedHeight,
	getResolvedWidth,
	getScroll,
	getScrollable,
	getScrollPercentage,
	getState,
	getStateAge,
	getStyle,
	getTabIndex,
	getTabOrder,
	getVerticalPadding,
	Hierarchy,
	hasBorder,
	hasBorderVisible,
	hasContent,
	hasDimensions,
	hasFocusable,
	hasHierarchy,
	hasInteractive,
	hasLabel,
	hasLabelText,
	hasPadding,
	hasPaddingValue,
	hasPosition,
	hasRenderable,
	hasScrollable,
	hasStateMachine,
	hexToColor,
	hide,
	Interactive,
	isAbsolute,
	isAtBottom,
	isAtTop,
	isClickable,
	isDirty,
	isDraggable,
	isFocusable,
	isFocused,
	isHoverable,
	isHovered,
	isInState,
	isInTabOrder,
	isKeyable,
	isLeaf,
	isParsingTags,
	isPercentage,
	isPressed,
	isRoot,
	isTextWrapped,
	isVisible,
	Label,
	LabelPosition,
	labelStore,
	makeFocusable,
	markClean,
	markDirty,
	moveBy,
	NULL_ENTITY,
	Padding,
	Position,
	packColor,
	Renderable,
	removeChild,
	removeLabel,
	resetContentStore,
	resetFocusState,
	resetLabelStore,
	Scrollable,
	ScrollbarVisibility,
	StateMachineStore,
	scrollBy,
	scrollTo,
	scrollToBottom,
	scrollToTop,
	sendEvent,
	setAbsolute,
	setBorder,
	setBorderChars,
	setClickable,
	setConstraints,
	setContent,
	setDimensions,
	setDraggable,
	setFocusable,
	setHoverable,
	setHovered,
	setInteractive,
	setKeyable,
	setLabel,
	setLabelOffset,
	setLabelPosition,
	setPadding,
	setPaddingAll,
	setPaddingHV,
	setParent,
	setParseTags,
	setPosition,
	setPressed,
	setScroll,
	setScrollable,
	setScrollbarVisibility,
	setScrollSize,
	setShrink,
	setStyle,
	setTabIndex,
	setTextAlign,
	setTextVAlign,
	setTextWrap,
	setVisible,
	setZIndex,
	shouldShrink,
	show,
	TextAlign,
	TextVAlign,
	unpackColor,
	updateStateAge,
} from './components';
// =============================================================================
// CORE - ECS Foundation
// =============================================================================
export type {
	BoxConfig,
	BubbleableEvent,
	BubbleableEventOptions,
	BubbleResult,
	ButtonConfig,
	Entity,
	EventHandler,
	EventMap,
	GetEntityEventBus,
	InputConfig,
	ListConfig,
	ScreenConfig,
	ScreenEventMap,
	System,
	TextConfig,
	UIEventMap,
	Unsubscribe,
	World,
} from './core';
export {
	BoxConfigSchema,
	ButtonConfigSchema,
	bubbleEvent,
	createBoxEntity,
	createBubbleableEvent,
	createButtonEntity,
	createEntityEventBusStore,
	createEventBus,
	createInputEntity,
	createListEntity,
	createScheduler,
	createScreenEntity,
	createTextEntity,
	createWorld,
	EventBus,
	filterClickable,
	filterDirty,
	filterFocusable,
	filterVisible,
	filterVisibleDirty,
	getChildEntities,
	getDeltaTime,
	getDescendantEntities,
	getRootEntities,
	InputConfigSchema,
	ListConfigSchema,
	LoopPhase,
	queryBorder,
	queryContent,
	queryFocusable,
	queryHierarchy,
	queryInteractive,
	queryPadding,
	queryRenderable,
	queryScrollable,
	resetWorld,
	Scheduler,
	ScreenConfigSchema,
	sortByDepth,
	sortByTabIndex,
	sortByZIndex,
	TextConfigSchema,
} from './core';

// =============================================================================
// SCHEMAS - Zod Validation
// =============================================================================
export type {
	ColorString,
	Dimension,
	NonNegativeInt,
	Percentage,
	PositionValue,
	PositiveInt,
} from './schemas';
export {
	ColorStringSchema,
	DimensionSchema,
	NonNegativeIntSchema,
	PercentageSchema,
	PositionValueSchema,
	PositiveIntSchema,
} from './schemas';

// =============================================================================
// SYSTEMS - ECS Systems
// =============================================================================
export type {
	HitTestResult,
	InputEventType,
	InputSystemState,
	QueuedInputEvent,
	QueuedKeyEvent,
	QueuedMouseEvent,
} from './systems';
export {
	// Input system
	captureMouseTo,
	clearEntityInput,
	clearEventQueue,
	createInputSystem,
	// State machine system
	createStateMachineSystem,
	getEventQueue,
	getInputEventBus,
	getInteractiveEntityAt,
	getMouseCaptureEntity,
	getStateAgeStore,
	getSystemStateAge,
	hitTest,
	inputState,
	inputSystem,
	isMouseCaptured,
	pointInEntity,
	queryInputReceivers,
	queryStateMachine,
	queueKeyEvent,
	queueMouseEvent,
	registerInputSystem,
	registerStateMachineSystem,
	releaseMouse,
	resetInputState,
	resetStateAge,
	stateMachineSystem,
	updateStateAges,
} from './systems';
// =============================================================================
// TERMINAL - Input Parsing
// =============================================================================
export type {
	FocusEvent,
	KeyEvent,
	KeyName,
	MouseAction,
	MouseButton,
	MouseEvent,
	MouseProtocol,
	ParseMouseResult,
} from './terminal';
export {
	FocusEventSchema,
	isMouseBuffer,
	isMouseSequence,
	KeyEventSchema,
	MouseEventSchema,
	parseKeyBuffer,
	parseKeySequence,
	parseMouseSequence,
} from './terminal';
// =============================================================================
// UTILS - Utility Functions
// =============================================================================
export type { BoxChars, Cell, CellBuffer, RenderBoxOptions, TextAlign, WrapOptions } from './utils';
export {
	BOX_ASCII,
	BOX_BOLD,
	BOX_DASHED,
	BOX_DOUBLE,
	BOX_ROUNDED,
	BOX_SINGLE,
	alignLine,
	bufferToString,
	charsetToBoxChars,
	createCellBuffer,
	fillRect,
	getVisibleWidth,
	padHeight,
	renderBox,
	renderHLine,
	renderText,
	renderVLine,
	stripAnsi,
	truncate,
	wordWrap,
	wrapText,
} from './utils';
