/**
 * blECSd Terminal Game Library
 *
 * A modern terminal game library built on TypeScript and ECS architecture.
 *
 * @packageDocumentation
 */

// =============================================================================
// VERSION
// =============================================================================
export const VERSION = '0.0.1';

// =============================================================================
// COMPONENTS - ECS Components and Helpers
// =============================================================================
export type {
	BorderCharset,
	BorderData,
	BorderOptions,
	ButtonEvent,
	ButtonState,
	ButtonStore,
	CheckboxDisplay,
	CheckboxDisplayOptions,
	CheckboxEvent,
	CheckboxState,
	CheckboxStore,
	ContentData,
	ContentOptions,
	DimensionConstraints,
	DimensionsData,
	DimensionValue,
	FocusableData,
	FocusableOptions,
	// Form
	FormFieldValue,
	FormResetCallback,
	FormStore,
	FormSubmitCallback,
	FormValues,
	HierarchyData,
	InteractiveData,
	InteractiveOptions,
	LabelData,
	LabelOptions,
	PaddingData,
	PaddingOptions,
	PositionData,
	// ProgressBar
	ProgressBarDisplay,
	ProgressBarDisplayOptions,
	ProgressBarStore,
	ProgressChangeCallback,
	ProgressCompleteCallback,
	// RadioButton
	RadioButtonDisplay,
	RadioButtonDisplayOptions,
	RadioButtonEvent,
	RadioButtonState,
	RadioButtonStore,
	RadioSelectCallback,
	RadioSetStore,
	RenderableData,
	ScrollableData,
	ScrollableOptions,
	ScrollPercentage,
	ScrollPosition,
	StyleData,
	StyleOptions,
	// TextInput
	CursorConfig,
	CursorConfigOptions,
	CursorModeType,
	TextInputAction,
	TextInputConfig,
	TextInputConfigOptions,
	TextInputEvent,
	TextInputState,
	TextInputStore,
} from './components';
export {
	// Dimensions
	AUTO_DIMENSION,
	// Hierarchy
	appendChild,
	appendContent,
	// Button
	attachButtonBehavior,
	// Checkbox
	attachCheckboxBehavior,
	// State Machine
	attachStateMachine,
	BORDER_ASCII,
	BORDER_BOLD,
	BORDER_DOUBLE,
	BORDER_ROUNDED,
	BORDER_SINGLE,
	// Border
	Border,
	BorderType,
	blur,
	// Button
	buttonStore,
	BUTTON_STATE_MACHINE_CONFIG,
	Content,
	canScroll,
	canSendEvent,
	// Checkbox
	checkboxStore,
	checkCheckbox,
	CHECKBOX_STATE_MACHINE_CONFIG,
	clearButtonCallbacks,
	clearCheckboxCallbacks,
	clearCheckboxDisplay,
	clearContent,
	clearInteractionState,
	// Renderable
	colorToHex,
	contentStore,
	DEFAULT_BG,
	DEFAULT_BORDER_BG,
	DEFAULT_BORDER_FG,
	DEFAULT_CHECKED_CHAR,
	DEFAULT_FG,
	DEFAULT_FOCUS_BG,
	DEFAULT_FOCUS_FG,
	DEFAULT_HOVER_BG,
	DEFAULT_HOVER_FG,
	DEFAULT_UNCHECKED_CHAR,
	Dimensions,
	disableButton,
	disableCheckbox,
	decodePercentage,
	detach,
	detachStateMachine,
	disableAllBorders,
	enableAllBorders,
	enableButton,
	enableCheckbox,
	encodePercentage,
	Focusable,
	focus,
	focusNext,
	focusNextField,
	focusPrev,
	focusPrevField,
	// Form
	formStore,
	attachFormBehavior,
	autoRegisterFields,
	clearFormCallbacks,
	getFieldName,
	getFieldValue,
	getFormFields,
	getFormTabOrder,
	getFormValues,
	handleFormKeyPress,
	isForm,
	isFormKeysEnabled,
	isFormSubmitOnEnter,
	onFormReset,
	onFormSubmit,
	registerFormField,
	resetForm,
	resetFormStore,
	setFieldValue,
	submitForm,
	unregisterFormField,
	getAncestors,
	getBorder,
	getBorderChar,
	getButtonState,
	getCheckboxChar,
	getCheckboxDisplay,
	getCheckboxState,
	getChildAt,
	getChildIndex,
	getChildren,
	getContent,
	getContentData,
	getContentHash,
	getContentLength,
	getDepth,
	getDescendants,
	getDimensions,
	getFirstChild,
	getFocusable,
	getFocusedEntity,
	getHierarchy,
	getHorizontalPadding,
	getInteractive,
	// Label
	getLabel,
	getLabelPosition,
	getLabelText,
	getLastChild,
	getNextSibling,
	getPadding,
	getParent,
	// Position
	getPosition,
	getPreviousState,
	getPrevSibling,
	getRenderable,
	getResolvedHeight,
	getResolvedWidth,
	getScroll,
	getScrollable,
	getScrollPercentage,
	getState,
	getStateAge,
	getStyle,
	getTabIndex,
	getTabOrder,
	getText,
	getVerticalPadding,
	handleButtonKeyPress,
	handleCheckboxKeyPress,
	Hierarchy,
	hasBorder,
	hasBorderVisible,
	hasContent,
	hasDimensions,
	hasFocusable,
	hasHierarchy,
	hasInteractive,
	hasLabel,
	hasLabelText,
	hasPadding,
	hasPaddingValue,
	hasPosition,
	hasRenderable,
	hasScrollable,
	hasStateMachine,
	hexToColor,
	hide,
	Interactive,
	insertAfter,
	insertAt,
	insertBefore,
	isAbsolute,
	isButton,
	isButtonDisabled,
	isButtonFocused,
	isButtonHovered,
	isButtonInState,
	isButtonPressed,
	isCheckbox,
	isCheckboxDisabled,
	isCheckboxInState,
	isChecked,
	isAtBottom,
	isAtTop,
	isClickable,
	isDetached,
	isDirty,
	isDraggable,
	isEffectivelyVisible,
	isFocusable,
	isFocused,
	isHoverable,
	isHovered,
	isInState,
	isInTabOrder,
	isKeyable,
	isLeaf,
	isParsingTags,
	isPercentage,
	isPressed,
	isRoot,
	isTextWrapped,
	isUnchecked,
	isVisible,
	Label,
	LabelPosition,
	labelStore,
	makeFocusable,
	markClean,
	markDirty,
	moveBy,
	NULL_ENTITY,
	onButtonPress,
	onCheckboxChange,
	Padding,
	Position,
	packColor,
	prepend,
	pressButton,
	// ProgressBar
	progressBarStore,
	ProgressOrientation,
	attachProgressBarBehavior,
	clearProgressBarCallbacks,
	clearProgressBarDisplay,
	completeProgress,
	decrementProgress,
	DEFAULT_EMPTY_CHAR,
	DEFAULT_EMPTY_CHAR_VERTICAL,
	DEFAULT_FILL_CHAR,
	DEFAULT_FILL_CHAR_VERTICAL,
	getProgress,
	getProgressBarDisplay,
	getProgressEmptyChar,
	getProgressFillChar,
	getProgressMax,
	getProgressMin,
	getProgressOrientation,
	getProgressPercentage,
	incrementProgress,
	isProgressBar,
	isProgressComplete,
	isShowingPercentage,
	onProgressChange,
	onProgressComplete,
	renderProgressString,
	resetProgress,
	resetProgressBarStore,
	setProgress,
	setProgressBarDisplay,
	setProgressOrientation,
	setProgressRange,
	setShowPercentage,
	// RadioButton
	RADIO_BUTTON_STATE_MACHINE_CONFIG,
	radioButtonStore,
	radioSetStore,
	attachRadioButtonBehavior,
	attachRadioSetBehavior,
	clearRadioButtonDisplay,
	clearRadioSetCallbacks,
	DEFAULT_RADIO_SELECTED_CHAR,
	DEFAULT_RADIO_UNSELECTED_CHAR,
	deselectRadioButton,
	disableRadioButton,
	enableRadioButton,
	getRadioButtonChar,
	getRadioButtonDisplay,
	getRadioButtonsInSet,
	getRadioButtonState,
	getRadioSet,
	getRadioValue,
	getSelectedButton,
	getSelectedValue,
	handleRadioButtonKeyPress,
	isRadioButton,
	isRadioButtonDisabled,
	isRadioButtonInState,
	isRadioSelected,
	isRadioSet,
	onRadioSelect,
	resetRadioButtonStore,
	selectRadioButton,
	selectRadioByValue,
	sendRadioButtonEvent,
	setRadioButtonDisplay,
	setRadioSet,
	setRadioValue,
	Renderable,
	removeChild,
	removeLabel,
	resetButtonStore,
	resetCheckboxStore,
	resetContentStore,
	resetFocusState,
	resetLabelStore,
	Scrollable,
	ScrollbarVisibility,
	StateMachineStore,
	scrollBy,
	scrollTo,
	scrollToBottom,
	scrollToTop,
	sendButtonEvent,
	sendCheckboxEvent,
	sendEvent,
	setAbsolute,
	setBorder,
	setBorderChars,
	setChecked,
	setCheckboxDisplay,
	setClickable,
	setConstraints,
	setContent,
	setDimensions,
	setDraggable,
	setFocusable,
	setHoverable,
	setHovered,
	setInteractive,
	setKeyable,
	setLabel,
	setLabelOffset,
	setLabelPosition,
	setPadding,
	setPaddingAll,
	setPaddingHV,
	setParent,
	setParseTags,
	setPosition,
	setPressed,
	setScroll,
	setScrollable,
	setScrollbarVisibility,
	setScrollSize,
	setShrink,
	setStyle,
	setTabIndex,
	setText,
	setTextAlign,
	setTextVAlign,
	setTextWrap,
	setVisible,
	setZIndex,
	shouldShrink,
	show,
	TextAlign,
	TextVAlign,
	toggle,
	// TextInput
	TEXT_INPUT_STATE_MACHINE_CONFIG,
	textInputStore,
	attachTextInputBehavior,
	blurTextInput,
	clearSelection,
	clearTextInputCallbacks,
	clearTextInputError,
	CursorMode,
	DEFAULT_CENSOR_CHAR,
	DEFAULT_CURSOR_BLINK_MS,
	DEFAULT_CURSOR_BLOCK_CHAR,
	DEFAULT_CURSOR_LINE_CHAR,
	DEFAULT_PLACEHOLDER,
	disableTextInput,
	emitCancel,
	emitSubmit,
	emitValueChange,
	enableTextInput,
	endEditingTextInput,
	focusTextInput,
	getCensorChar,
	getCursorChar,
	getCursorConfig,
	getCursorDisplayText,
	getCursorMode,
	getCursorPos,
	getMaxLength,
	getNormalizedSelection,
	getPlaceholder,
	getSelection,
	getTextInputConfig,
	getTextInputState,
	handleTextInputKeyPress,
	hasSelection,
	isCursorBlinkEnabled,
	isCursorVisible,
	isMultiline,
	isSecretMode,
	isTextInput,
	isTextInputDisabled,
	isTextInputEditing,
	isTextInputError,
	isTextInputFocused,
	isTextInputInState,
	maskValue,
	moveCursor,
	onTextInputCancel,
	onTextInputChange,
	onTextInputSubmit,
	resetCursorBlink,
	resetTextInputStore,
	sendTextInputEvent,
	setCursorBlinkEnabled,
	setCursorConfig,
	setCursorMode,
	setCursorPos,
	setSelection,
	setTextInputConfig,
	setTextInputError,
	startEditingTextInput,
	toggleCursorMode,
	toggleCheckbox,
	uncheckCheckbox,
	unpackColor,
	updateStateAge,
} from './components';
// =============================================================================
// CORE - ECS Foundation
// =============================================================================
export type {
	BoxConfig,
	BubbleableEvent,
	BubbleableEventOptions,
	BubbleResult,
	ButtonConfig,
	CheckboxConfig,
	Entity,
	EventHandler,
	EventMap,
	FormConfig,
	GetEntityEventBus,
	InputConfig,
	ListConfig,
	PositionValue,
	ProgressBarConfig,
	RadioButtonConfig,
	RadioSetConfig,
	ScreenConfig,
	ScreenEventMap,
	ShrinkBox,
	System,
	TextareaConfig,
	TextboxConfig,
	TextConfig,
	UIEventMap,
	Unsubscribe,
	World,
} from './core';
export {
	applyShrink,
	BoxConfigSchema,
	ButtonConfigSchema,
	bubbleEvent,
	calculateShrinkSize,
	centerPosition,
	CheckboxConfigSchema,
	clampPosition,
	createBoxEntity,
	createBubbleableEvent,
	createButtonEntity,
	createCheckboxEntity,
	createEntityEventBusStore,
	createEventBus,
	createFormEntity,
	createInputEntity,
	createListEntity,
	createProgressBarEntity,
	createRadioButtonEntity,
	createRadioSetEntity,
	createScheduler,
	createScreenEntity,
	createTextareaEntity,
	createTextboxEntity,
	createTextEntity,
	createWorld,
	EventBus,
	filterClickable,
	filterDirty,
	filterFocusable,
	filterVisible,
	filterVisibleDirty,
	FormConfigSchema,
	getChildEntities,
	getDeltaTime,
	getDescendantEntities,
	getRootEntities,
	getShrinkBox,
	getShrinkHeight,
	getShrinkWidth,
	InputConfigSchema,
	isKeywordPosition,
	isPercentagePosition,
	ListConfigSchema,
	LoopPhase,
	PositionValueSchema,
	parsePosition,
	parsePositionWithNegative,
	percentOffsetPosition,
	percentPosition,
	ProgressBarConfigSchema,
	RadioButtonConfigSchema,
	RadioSetConfigSchema,
	queryBorder,
	queryContent,
	queryFocusable,
	queryHierarchy,
	queryInteractive,
	queryPadding,
	queryRenderable,
	queryScrollable,
	resetWorld,
	resolvePosition,
	resolvePositionClamped,
	Scheduler,
	ScreenConfigSchema,
	sortByDepth,
	sortByTabIndex,
	sortByZIndex,
	TextareaConfigSchema,
	TextboxConfigSchema,
	TextConfigSchema,
} from './core';

// =============================================================================
// SCHEMAS - Zod Validation
// =============================================================================
export type { ColorString, Dimension, NonNegativeInt, Percentage, PositiveInt } from './schemas';
export {
	ColorStringSchema,
	DimensionSchema,
	NonNegativeIntSchema,
	PercentageSchema,
	PositiveIntSchema,
} from './schemas';

// =============================================================================
// SYSTEMS - ECS Systems
// =============================================================================
export type {
	HitTestResult,
	InputEventType,
	InputSystemState,
	QueuedInputEvent,
	QueuedKeyEvent,
	QueuedMouseEvent,
} from './systems';
export {
	// Input system
	captureMouseTo,
	clearEntityInput,
	clearEventQueue,
	createInputSystem,
	// State machine system
	createStateMachineSystem,
	getEventQueue,
	getInputEventBus,
	getInteractiveEntityAt,
	getMouseCaptureEntity,
	getStateAgeStore,
	getSystemStateAge,
	hitTest,
	inputState,
	inputSystem,
	isMouseCaptured,
	pointInEntity,
	queryInputReceivers,
	queryStateMachine,
	queueKeyEvent,
	queueMouseEvent,
	registerInputSystem,
	registerStateMachineSystem,
	releaseMouse,
	resetInputState,
	resetStateAge,
	stateMachineSystem,
	updateStateAges,
} from './systems';
// =============================================================================
// TERMINAL - Input Parsing
// =============================================================================
export type {
	FocusEvent,
	KeyEvent,
	KeyName,
	MouseAction,
	MouseButton,
	MouseEvent,
	MouseProtocol,
	ParseMouseResult,
} from './terminal';
export {
	FocusEventSchema,
	isMouseBuffer,
	isMouseSequence,
	KeyEventSchema,
	MouseEventSchema,
	parseKeyBuffer,
	parseKeySequence,
	parseMouseSequence,
} from './terminal';
// =============================================================================
// UTILS - Utility Functions
// =============================================================================
export type {
	BoxChars,
	Cell,
	CellBuffer,
	RenderBoxOptions,
	StyleAttr,
	StyleInput,
	WrapOptions,
} from './utils';
export {
	AttrFlags,
	alignLine,
	attrsToStyle,
	BOX_ASCII,
	BOX_BOLD,
	BOX_DASHED,
	BOX_DOUBLE,
	BOX_ROUNDED,
	BOX_SINGLE,
	bufferToString,
	charsetToBoxChars,
	createCellBuffer,
	decodeStyleAttr,
	encodeStyleAttr,
	fillRect,
	getVisibleWidth,
	padHeight,
	renderBox,
	renderHLine,
	renderText,
	renderVLine,
	sattr,
	sattrAddFlag,
	sattrCopy,
	sattrEmpty,
	sattrEqual,
	sattrFromStyleData,
	sattrHasFlag,
	sattrInvert,
	sattrMerge,
	sattrRemoveFlag,
	stripAnsi,
	styleToAttrs,
	truncate,
	wordWrap,
	wrapText,
} from './utils';
